[package]
name = "burn_tensorflow_tut"
version = "0.1.0"
edition = "2021"

[dependencies]
# burn = "0.14.0"
burn = { git = "https://github.com/tracel-ai/burn.git", features = [
    "wgpu",
    "train",
    "vision",
] }
